select * from customer_shopping_behavior

--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) total_revenue
from customer_shopping_behavior
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase 
--amount?

select customer_id,purchase_amount
from customer_shopping_behavior
where discount_applied = 'Yes' and purchase_amount > 
(select avg(purchase_amount) from customer_shopping_behavior)

--Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased,round(avg(review_rating),2) avg_review_rating
from customer_shopping_behavior
group by item_purchased
order by avg_review_rating desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,avg(purchase_amount) avg_purchase_amount
from customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,count(*) total_customers, avg(purchase_amount) avg_spend,
sum(purchase_amount) total_revenue
from customer_shopping_behavior
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased,100 * sum(case when discount_applied = 'Yes' then 1 else 0 
end) / count(*) discount_rate
from customer_shopping_behavior
group by item_purchased
order by discount_rate desc

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

with customer_type as
(select customer_id,previous_purchases,case when previous_purchases = 1 then 'New' 
when previous_purchases between 2 and 10 then 'Returning' 
else 'Loyal' end as customer_segment
from customer_shopping_behavior)

select customer_segment,count(*) customers
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 

with cte as
(select category,item_purchased,count(*) total_orders,row_number() over(partition by category order by count(*) 
desc) item_rank
from customer_shopping_behavior
group by category,item_purchased)

select category,item_purchased,total_orders,item_rank
from cte 
where item_rank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to
--subscribe?

select subscription_status,count(customer_id) repeat_buyers
from customer_shopping_behavior
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 

select age_group,sum(purchase_amount) total_revenue
from customer_shopping_behavior
group by age_group